name: simple_networking
description: Network layer for Simple App

publish_to: 'none'

environment:
  sdk: ">=2.17.3 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

  dart_code_metrics: ^4.16.0


flutter:
#  generate: true
  uses-material-design: true